linters:
  disable-all: true
  enable:
    - errcheck # Finds unchecked errors.
    - gosimple # Finds potential simplifications. See also: https://staticcheck.io/docs/checks/#S.
    - govet # See "go tool vet help".
    - ineffassign # Finds assignments that are not used.
    - staticcheck # See also: https://staticcheck.io/docs/checks/#SA.
    - typecheck # Parses and type-checks Go code.
    - unused # Finds unused consts, vars, funcs and types.

    # Enabled manually:
    - asciicheck # Finds non-ASCII identifiers.
    - errorlint # Finds problems with error wrapping.
    - goconst # Finds repeated strings that could be replaced by a const.
    - gocyclo # Finds funcs with high cyclomatic complexity.
    - godot # Finds comments that do not end with a period.
    - gofumpt # Finds files that were not gofumpt-ed.
    - lll # Finds lines that exceed the line length limit.
    - makezero # Finds combinations of `make([]T, n)` and `append()`.
    - nakedret # Finds naked returns.
    - nilnil # Finds `return nil, nil`.
    - prealloc # Finds slice declarations that could be pre-allocated.
    - stylecheck # See also: https://staticcheck.io/docs/checks/#ST.
    - unconvert # Finds unnecessary type conversions.
    - unparam # Finds unused function parameters.

linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 5
    
  stylecheck:
    checks:
      - all
      - -ST1003 # To keep the defines in line with the way they are defined by Bachmann we need to disable the ALL_CAPS check. 